project:
  type: book

book:
  title: "manuscript"
  author: "Norah Jones"
  date: "2/16/2026"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-model.qmd
    - 03-estimation.qmd
    - 04-conclusion.qmd
  appendices:
    - 11-detail-comp.qmd
    - 12-supplement.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto
  echo: false
  message: false
  warning: false

crossref:
  eq-prefix: "Eq."

knitr:
  opts_chunk: 
    fig.align: center
    fig.retina: 3
    fig.width: 6
    fig.height: 3
    out.width: 90%
    collapse: true